# Generated by Django 2.1.2 on 2018-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermark',
            name='classteacher',
        ),
        migrations.RemoveField(
            model_name='teachermark',
            name='studentpercentage',
        ),
        migrations.AddField(
            model_name='teachermark',
            name='rollnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachermark',
            name='marks_obtained',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachermark',
            name='maxtestmarks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachermark',
            name='section',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teachermark',
            name='standard',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachermark',
            name='studentname',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
