# Generated by Django 2.1.1 on 2018-10-20 12:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0002_auto_20181018_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), size=None)),
                ('rollnumber', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('standard', models.IntegerField(null=True)),
                ('section', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_test', models.CharField(max_length=200)),
                ('maxtestmarks', models.IntegerField(null=True)),
                ('marks_obtained', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='teachermark',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='subject_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolerp.Subjects'),
        ),
    ]
