# Generated by Django 2.1.1 on 2018-10-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0003_auto_20181020_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
