# Generated by Django 2.1.1 on 2018-10-20 13:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0004_auto_20181020_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('standard', models.IntegerField(null=True)),
                ('section', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_test', models.CharField(max_length=200)),
                ('maxtestmarks', models.IntegerField(null=True)),
                ('marks_obtained', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='maxtestmarks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_of_the_test',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='rollnumber',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='studentname',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolerp.StudentDetail'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolerp.Test'),
        ),
    ]
