# Generated by Django 2.1.1 on 2018-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0005_auto_20181020_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='marks_obtained',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='marks_obtained',
            field=models.IntegerField(null=True),
        ),
    ]
