# Generated by Django 2.1.1 on 2018-10-21 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('schoolerp', '0006_auto_20181021_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('numstudents', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profession', models.CharField(choices=[('TEACHER', 'teacher'), ('ADMIN', 'admin'), ('PRINCIPAL', 'principal')], default='TEACHER', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('rollnumber', models.IntegerField(null=True)),
                ('parentname', models.CharField(blank=True, max_length=50)),
                ('parentnum', models.IntegerField(null=True)),
                ('dob', models.DateField(max_length=8)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolerp.Classroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='subject_details',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='clas',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='classroom',
            name='classteacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolerp.Profile'),
        ),
    ]
