# Generated by Django 2.1.1 on 2018-10-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0009_auto_20181021_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='standard',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
