# Generated by Django 2.1.1 on 2018-10-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0011_auto_20181021_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolerp.Classroom'),
        ),
        migrations.AddField(
            model_name='test',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolerp.Exam'),
        ),
    ]
