# Generated by Django 2.1.1 on 2018-10-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0013_auto_20181022_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='evaluated_by',
            new_name='evaluatedby',
        ),
    ]
