# Generated by Django 2.1.1 on 2018-10-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolerp', '0014_auto_20181024_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolerp.Classroom'),
        ),
    ]
